# subworkflow - slides
# Contributors: @lachlandeer

import glob, os

# --- Importing Configuration Files --- #

configfile: "../../" + "config.yaml"

ROOT = "../../"
HERE = ROOT + config["src_slides"]
LIB  = ROOT  + config["src_lib"]

# --- Variable Declarations ---- #
runR = "Rscript --no-save --no-restore --verbose"
logAll = "2>&1"

# --- Build Rules ---#

rule build_slides:
    input:
        slide_rmd = HERE + "slides.Rmd",
        runner = LIB + "knit_xaringan.R",
        css = HERE + "lagonbleu.css"
    output:
        slides = ROOT + "slides.html"
    log:
        ROOT + config["log"] + "slides.Rout"
    shell:
        "{runR} {input.runner} {input.slide_rmd} \
                    {output.slides} > {log} {logAll}"
