# subworkflow - slides
# Contributors: @lachlandeer

import glob, os

# --- Importing Configuration Files --- #

configfile: "../../" + "config.yaml"

ROOT = "../../"
HERE = ROOT + config["src_slides"]
LIB  = ROOT  + config["src_lib"]

# --- Variable Declarations ---- #
runR = "Rscript --no-save --no-restore --verbose"
logAll = "2>&1"

# --- Dictionary --- #

SECTIONS = [
            "intro",
            "mathjax",
            "r-code",
            "css-info",
            "thanks"
            ]

# --- Build Rules ---#

rule build_slides:
    input:
        slide_rmd = HERE + "slides.Rmd",
        runner = LIB + "knit_xaringan.R",
        css = ROOT + "lagonbleu.css"
    output:
        slides = ROOT + "slides.html"
    log:
        ROOT + config["log"] + "slides.Rout"
    shell:
        "{runR} {input.runner} {input.slide_rmd} \
                    {output.slides} > {log} {logAll}"

rule bundle_rmds:
    input:
        metadata = "slide_config.yaml",
        section = expand("{iSection}.Rmd",  iSection = SECTIONS)
    output:
        HERE + "slides.Rmd"
    shell:
        "sed -n 'p' {input.metadata} {input.section} > {output} "
